// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmKeEtBY2TWbM7YQBbPmZZr0hgjH9re9c',
    appId: '1:1085151263821:web:2c2c5d68ea109fbf25f004',
    messagingSenderId: '1085151263821',
    projectId: 'palipa-chat-a1dca',
    authDomain: 'palipa-chat-a1dca.firebaseapp.com',
    databaseURL: 'https://palipa-chat-a1dca-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'palipa-chat-a1dca.appspot.com',
    measurementId: 'G-39Y1Y1327Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbMUeJUO3IUbxXx2biZGSpj20i0HoLQL8',
    appId: '1:1085151263821:android:2d928d0b5397f9de25f004',
    messagingSenderId: '1085151263821',
    projectId: 'palipa-chat-a1dca',
    databaseURL: 'https://palipa-chat-a1dca-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'palipa-chat-a1dca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUIRQZDAqN2Tv0iFQipibck2jWimE9MF8',
    appId: '1:1085151263821:ios:8fe947cad6588caa25f004',
    messagingSenderId: '1085151263821',
    projectId: 'palipa-chat-a1dca',
    databaseURL: 'https://palipa-chat-a1dca-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'palipa-chat-a1dca.appspot.com',
    iosClientId: '1085151263821-53cl1nl2d6eqahku3agr2p8lhdh0qcb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.palipaChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUIRQZDAqN2Tv0iFQipibck2jWimE9MF8',
    appId: '1:1085151263821:ios:8fe947cad6588caa25f004',
    messagingSenderId: '1085151263821',
    projectId: 'palipa-chat-a1dca',
    databaseURL: 'https://palipa-chat-a1dca-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'palipa-chat-a1dca.appspot.com',
    iosClientId: '1085151263821-53cl1nl2d6eqahku3agr2p8lhdh0qcb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.palipaChatApp',
  );
}
